### ISSUE TITLE
Welcome letter not updated

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#100]
Use the updated version of Welcome Letter (shared with Manas on 17 Feb, 2016).
Please take care that the logos are not distorted in the final display.

**Comment by mouparnadas** [comment]
The welcome letter has been updated as per shared document.
Please review and close the issue.

**Comment by manasghosh81** [comment]
As decided,the font of welcome letter is modified to Helvatica. There is one space before and after the |
on last line between phone no and email as follows
24×7 Toll-free Support: 1800-4190-901 | Email: oxfordmathsindia@oup.com

**Comment by kirti-sharma** [comment]
Fixed.
