### ISSUE TITLE
school expiry message from School Admin login

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfordMath_UAT#102]
hi,
  while doing UAT of license expiry module from school Admin profile, I just noticed the message that school admin gets. It says 'your license is going to be expired. Please contact …..’ 

Please change this school expiry message to 'Your Oxford Maths school licenses are going to be expired. Please contact .....'.

**Comment by madhumitadey** [comment]
**It should read as:**

Dear Madhumita Dey,

Your Oxford Maths school licenses will expire on 4/30/2016 by 12:00:00 am.
Please contact Oxford Maths team for renewal at the earliest.

Best wishes,
Oxford Maths Team

**TCS: Please make changes in the content as per the text given above. Line spacing should be proper as shown.**

**Comment by sumitmago** [comment]
ok. closed.
