### ISSUE TITLE
Tasks that are attempted three times are not shown in completed task tab

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#103]
See word doc.

[Completed tasks.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/152407/Completed.tasks.docx)

**Comment by manasghosh81** [comment]
@madhumitadey : As per functionality, tasks is considered complete only when the task end date has passed. Then only it gets moved to Completed Task.

**Comment by madhumitadey** [comment]
Okay.

**Comment by madhumitadey** [comment]
As per FSD, a task should move to completed tab when it is attempted three times. 

Please refer to the screenshot from the fsd below for reference.

![image](https://cloud.githubusercontent.com/assets/16831474/13450388/d876d27a-e05a-11e5-902b-81eeabddb6a6.png)

**Comment by manasghosh81** [comment]
As per FSD it is not a valid defect.Please recheck and close it

**Comment by somabanerjee** [comment]
Hi! We are referring to v 2.2 of the FSD. To categorise a task as completed, one of two criteria must be met (as can be verified from the screenshot in the comment above). It is an either/or condition. Please go back to the FSD, review and fix.

**Comment by manasghosh81** [comment]
@somabanerjee : This is Subha. We will make this change to student dashboard only, however for calculation in reports, the averages and all are done based on completed tasks which means for which end date has reached. 

![image](https://cloud.githubusercontent.com/assets/12447431/13454851/df3349ac-e07f-11e5-8e13-933ef25a72c5.png)

![image](https://cloud.githubusercontent.com/assets/12447431/13454874/f4fd5192-e07f-11e5-8953-05e068b602f4.png)

**Comment by somabanerjee** [comment]
@Subha For calculation in reports, the task completion date should be the only criteria, as discussed and agreed upon. This change is needed in the student dashboard alone.

**Comment by manasghosh81** [comment]
@somabanerjee , @madhumitadey : This is done, please check.

**Comment by madhumitadey** [comment]
This is working fine now.
