### ISSUE TITLE
Wrong notification message and functionality of more than 3 attempts on resources page

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#104]
Check word doc please.

[Test case 35 (Student login).docx](https://github.com/OUPMATH/OxfordMath_UAT/files/152492/Test.case.35.Student.login.docx)

**Comment by mouparnadas** [comment]
The message and functionality are updated in assigned OH of student from resource page.
The user will be alerted and no re-direction will happen.
Please retest and close the issue.

**Comment by madhumitadey** [comment]
This is working fine now.
