### ISSUE TITLE
Performance report downloading instead of printing!

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#105]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Student login credential and click on login.
Step 3  Select Reports from the side scroll bar
Step 4  Click on the Print All button

Present functionality: Performance report downloads on the system in pdf format.
Required functionality: Performance report should get printed instead.

**Comment by manasghosh81** [comment]
@kirti-sharma : As per the functionality the PDF should get downloaded and user should select print from PDF to print the report.

**Comment by kirti-sharma** [comment]
Fine
