### ISSUE TITLE
The activity tab is not visible on the dashboard of Student login

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#106]
The activity tab is not visible on the dashboard.
Please check screenshot from fsd for reference.

![image](https://cloud.githubusercontent.com/assets/16831474/13450492/f5ea50b0-e05b-11e5-8a46-9d2732153f74.png)

This is screenshot of the dashboard that is currently visible.
![image](https://cloud.githubusercontent.com/assets/16831474/13450499/01e87626-e05c-11e5-9c69-efc4b40a63ce.png)

**Comment by manasghosh81** [comment]
@madhumitadey : This is Subha. This has been changed later after discussion with Sumit and Soma as the screen was looking cluttered. That's the reason the slider will contain "My Activity" when seeing "My Tasks" on the actual screen and vice versa so that student can toggle if required.

**Comment by madhumitadey** [comment]
Okay.
