### ISSUE TITLE
Activity not created

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#107]
Please see word doc.

[Notification not created.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/154122/Notification.not.created.docx)

**Comment by manasghosh81** [comment]
@madhumitadey : This is Subha. The notification is generated at student's end. YOu will have to login using the student to which activity is assigned and you will be able to see the notification under "View notification" of the Student. Attached screenshot.

![image](https://cloud.githubusercontent.com/assets/12447431/13452231/146a3a68-e06c-11e5-88af-b088f45d26e5.png)

**Comment by madhumitadey** [comment]
Hi Subha, for this particular case, notification is not being generated (neither in teacher login, nor in student login). I am attaching word doc comprising detailed screenshots of the case. 

[Notification not created-1.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/154219/Notification.not.created-1.docx)

**Comment by manasghosh81** [comment]
Please recheck  this.

**Comment by somabanerjee** [comment]
@mayank2k2 The editors are unable to assign activities. Please vet. If needed, we will be happy to share more details with you.

**Comment by manasghosh81** [comment]
@somabanerjee : we are able to assign activities successfully. Can you pls clear cache and try again?

**Comment by manasghosh81** [comment]
@somabanerjee : We are not able to replicate this, activities are getting created successfully along with notification message sent to students. This problem may have happened as one of the servers were unreachable around 4:00 PM on 2/3. Sumit had reported this problem first post which we saw the same thing. Please retest this and close if everything is fine.

Thanks
Subha

**Comment by madhumitadey** [comment]
This is working fine now.
