### ISSUE TITLE
School detail not showing city

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#11]
Step 1: Search school with City: Noida
Issue: Result displays but  city is not showing in detail.
Expected: City should also display before state in the school details  

![school detail not showing city](https://cloud.githubusercontent.com/assets/16239450/12807046/b7b27bb8-cb31-11e5-92bb-255ab788de4a.JPG)

**Comment by manasghosh81** [comment]
This issue is fixed now .It will be available in UAT environment after next deployment

**Comment by mayank2k2** [comment]
working
