### ISSUE TITLE
Alert 

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#111]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Student login credential and click on login.
Step 3  Check the My task drpdown on the dashboard
Step 4  Select the lapsed  option from the dropdown
Step 5  Check the tile for the lapsed task

Click on a lapsed task.
The alert message pops up-- 'This task is already lapsed, your score will not be sent to your teacher.'
Modify the message to 'This task has already lapsed. Your score will not be sent to your teacher. '

**Comment by mouparnadas** [comment]
The change has been implemented in QA. This will be available in next deployment.

**Comment by kirti-sharma** [comment]
Fixed.
