### ISSUE TITLE
can't bulk export for student Promotion

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#112]
Please review as a school admin "School Admin will generate the Export Excel in bulk upload format and make changes to the Class Code and section name for each candidate"

I my school has 1200 student, i can only export 5 student at a time there is no way to bulk export in utility section.  

![image](https://cloud.githubusercontent.com/assets/16239450/13490653/ef8012ac-e153-11e5-8854-3698306d3273.png)

**Comment by manasghosh81** [comment]
@mayank2k2 : This was never a requirement. It is clearly written in the FSD that exported excel will be generated in "bulk upload" format, not that it will export records for the whole school. It was discussed in a UAT call between soma, sumit, kirti as well and there also it was agreed that the header functions at the top of the table will be applicable to the number of rows shown within the table.

Can I ask, why are these changes coming so late? Was the FSD not reviewed properly before sign-off?

Regards
Subha

**Comment by sumitmago** [comment]
Hi,
               As per FSD language and as per discussion, expectation is that
1. ```
    School admin to take out previous year data (which includes all the licenses in use/bought for last academic year).
   ```
2. ```
    Make required changes in class, section, roll no. as per pass/failure status of each kid so that migration data is in ready format for coming academic year.
   ```
3. ```
    Pass on the sheet to OUP Admin
   ```
4. ```
    OUP admin upload at one go (the way it is happening in first year of school opening).
   ```

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by mayank2k2** [comment]
@manasghosh81 as discuss and seen yesterday, if we "Export All", the record exported are not maching with total no of records shown.

**Comment by manasghosh81** [comment]
I have check this in UAT.It is working fine.Please create a new school and upload students on this school and try this functionality.

**Comment by mayank2k2** [comment]
working fine
