### ISSUE TITLE
Notification page correction

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#113]
Open the OUP my maths url in a browser
Provide the Student login credential and click on login.
Click on the notification icon at the top of the dashboard
Select any notification from history.

Present functionality: In the message box, mousehover icon on the scroll bar is forbidden mouse cursor.
Required functionality: The mousehover icon on the scroll bar should be normal select pointer.
Also, make the changes given in the screenshot:
![image](https://cloud.githubusercontent.com/assets/16831643/13490248/8107b2be-e151-11e5-8804-0c3d1f9f0d4e.png)

**Comment by mouparnadas** [comment]
@kirti-sharma 
The notification message are as per the share template attached.
please review the text and confirm the changes.

**Comment by mouparnadas** [comment]
[Notification Template (1).zip](https://github.com/OUPMATH/OxfordMath_UAT/files/156611/Notification.Template.1.zip)

**Comment by kirti-sharma** [comment]
Text changes are fixed.
Present functionality: In the message box, mousehover icon on the scroll bar is forbidden mouse cursor.
Required functionality: The mousehover icon on the scroll bar should be normal select pointer.

**Comment by mouparnadas** [comment]
When the message is big the scroll bar is present and working fine.
For small messages the scroll bar is not required and hence forbidden appears.
It is the functionality of scroll bar element.

**Comment by kirti-sharma** [comment]
Forbidden pointer is fine for text body. 
The scroll bar is working fine but the mouse icon over scroll bar should be normal select pointer. Scrolling should not be done with forbidden pointer.

**Comment by manasghosh81** [comment]
@mayank2k2 :As discuss in our defect Triage meeting this is browser behavior(Google chrome).We do have any control over it.

N.B:The scroll bar  is working  the way you want in Firefox.

**Comment by kirti-sharma** [comment]
Alright.
