### ISSUE TITLE
Contact us notification message

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#114]
Step 1  User to open a browser.
Step 2  User should put the mymaths url and click on enter.
Step 3  Click on the “Contact Us” link
Step 4  Fill the contact us form. Select 'Request for' as 'Others'. Leave the message body blank.

Present functionality: Contact request is getting submitted.
Required functionality: Message body should be a mandatory field if user has selected Service request and Others in “Request For” option. Else it should be an optional field

Make the following textual change:
![image](https://cloud.githubusercontent.com/assets/16831643/13491588/3b7e4dea-e159-11e5-84fa-8c420fb56403.png)
![image](https://cloud.githubusercontent.com/assets/16831643/13491679/bfac3bea-e159-11e5-9a42-474f679f2a5b.png)

**Comment by mouparnadas** [comment]
Text updated. The changes will be available in next deployment.

**Comment by kirti-sharma** [comment]
Step 4 Fill the contact us form. Select 'Request for' as 'Service request'. Leave the message body blank.

Present functionality: Contact request is getting submitted.
Required functionality: Message body should be a mandatory field if user has selected Service request and Others in “Request For” option. Else it should be an optional field.

**Comment by manasghosh81** [comment]
This fix is available in UAT now.Please retest and close this

**Comment by kirti-sharma** [comment]
Fixed.
