### ISSUE TITLE
Task status text correction

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#115]
Step 1 Open the OUP my maths url in a browser
Step 2 Provide the Teacher login credential and click on login.
Step 3 Click on reports link
Step 4 Click the Task Status from the reports
Step 5 Fill the details and click on search
Step 6 Click on any one completion status link.

Modify text as shown below:
![image](https://cloud.githubusercontent.com/assets/16831643/13519808/0610b186-e201-11e5-8463-0779a7338511.png)

**Comment by manasghosh81** [comment]
![student wise report](https://cloud.githubusercontent.com/assets/12447431/13521523/3c395962-e20f-11e5-9477-1403c9a9ea97.png)

Please see the attached image.

**Comment by kirti-sharma** [comment]
Fixed.
