### ISSUE TITLE
Login Detail not found for uploaded users

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#12]
Step 1: Login with admin user, search school "test school 11"
Step 2: click on upload icon
Step 3: Click on File link for "4 feb" with status "No Error"  and action "Processed"
Step 4: File downloaded and open the file 

Issue: User Name empty 
Expected : File should have user name for further logins

**Comment by mouparnadas** [comment]
As per FSD, 
The username will be available at time of student promotion.
This list will be provided by SchoolAdmin.
This way user creation and promotion are discriminated.

**Comment by mayank2k2** [comment]
Now it is working
