### ISSUE TITLE
Back/close button functionality issue

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#120]
1.  Login using teacher credentials.
2.  Go to Reports-->Student performance.
3.  Search by any class and section name.
4.  Go the students details search result and select on Actions icon to view individual report.
5.  Student performance report gets generated. Click back button of the browser. 
6. Perform the steps 1–5. Click on Close button.

Present functionality: The ‘student details’ search results do not appear. User gets redirected to this page.
![image](https://cloud.githubusercontent.com/assets/16831474/13625195/fc87086c-e5da-11e5-9b1c-8baf189c6dd8.png)

Required functionality: On clicking the back/close button, the page should be redirected to ‘student details’ search result (shown below).

![image](https://cloud.githubusercontent.com/assets/16831474/13625198/0169f8ee-e5db-11e5-92d3-6eea30a50059.png)

This problem was raised in Github issue #108 as well.

**Comment by mayank2k2** [comment]
This is not working correctly, if we do below:

Login using teacher credentials. Go to Reports-->Student performance.Search by any class and section name.
1. Go the students details search result and select on Actions icon to view individual report.
2. Student performance report gets generated. 
3. Click close button or back of the browser.

Repeat step 1,2, 3 for another student.
The ‘student details’ search results do not appear. User gets redirected to search page.

![image](https://cloud.githubusercontent.com/assets/16239450/14663393/32b2c358-06de-11e6-9cc6-e0bf8f694bb5.png)
