### ISSUE TITLE
Uneven sizes of smileys on checkout page of OHs

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#123]
Uneven sizes of smileys on checkout page of OHs. Please check.

![image](https://cloud.githubusercontent.com/assets/16831474/13626097/7deea06e-e5e4-11e5-9508-c3ac259266d8.png)

**Comment by manasghosh81** [comment]
@madhumitadey : This is nothing we can do about it as it is a default functionality of the Zippy. Please check the screenshot below as taken from the Mymaths.co.uk website. 

Regards
Subha

![image](https://cloud.githubusercontent.com/assets/12447431/13626167/6cbe1864-e5e5-11e5-9f6e-8c7c511740d8.png)

**Comment by madhumitadey** [comment]
Okay
