### ISSUE TITLE
Uneven class names on the resource page 

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#124]
Error introduced. This was correct before.

Login using teacher credentials and go to resources link.

Change 'Class3' to '3' in the class dropdown list.

![image](https://cloud.githubusercontent.com/assets/16831474/13626573/287b6db0-e5e9-11e5-96d0-faebe6fcbc0c.png)

**This error is introduced in all the pages where class 3 is there in the dropdown list. Please correct it everywhere**
For example, on class performance page on Teacher login.

![image](https://cloud.githubusercontent.com/assets/16831474/13626839/83eba32a-e5eb-11e5-824e-d67c87190fb3.png)

Assign task page
![image](https://cloud.githubusercontent.com/assets/16831474/13626835/7bb53018-e5eb-11e5-9718-2a61e7b1bb37.png)

**Comment by manasghosh81** [comment]
@madhumitadey : The class name for Class 3 has been entered as "Class 3" while uploading. Please see the screenshot for Kamal Srivastava. Whatever class name user is using during upload will appear here. For Class 3, the class name is specified as "Class 3".

![image](https://cloud.githubusercontent.com/assets/12447431/13627619/9b9e2f00-e5f1-11e5-9c10-125e8d179083.png)

Please close this.

Regards
Subha

**Comment by madhumitadey** [comment]
Okay
