### ISSUE TITLE
Class performance print - usability issue

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#128]
Login as teacher.
Go to reports.
In class performance tab, search for one class. 
The search shows student performance comparison with 5 students per page.
Present functionality: Teacher is able to print only 5 students' performance at a time.
![image](https://cloud.githubusercontent.com/assets/16831643/13627079/b531ede8-e5ed-11e5-8905-f4ad04b878a3.png)

Required functionality: The teacher should have the option to print the performance of the whole class at one go.

**Comment by manasghosh81** [comment]
@kirti-sharma , @mayank2k2 : This is again the same issue with the check boxes and generic control - it had been discussed repeatedly that the select all checkboxes will work only on the rows shown in the screen - that's how it is working now. If this needs to be change, it should be a change throughout the application, which is not feasible right now.

Regards
Subha

**Comment by somabanerjee** [comment]
Hi Subha, 

While I understand your point, but it is most cumbersome from the user's perspective. We debated this issue internally before flagging it here. Frankly, I find myself  hard pressed to imagine that a teacher will be willing hit the print command eight or more times to see how a particular section has performed on a task. Will really appreciate a solution here since teachers will be interested in seeing class performance for specific tasks. 

Thanks,
Soma

**Comment by manasghosh81** [comment]
@sumitmago : cannot put any effort on this right now. We need to think what solution it can have during the support period

Regards
Subha

**Comment by sumitmago** [comment]
Hi,
               As we agreed during FSD to print report as shown on screen, let’s agree on improving report print output as discussed with Subha (increase no. of records in print output) and do it later in support period. Please place it under enhancement to be done in support.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by sumitmago** [comment]
Hi,
               Further, we also agreed to get tabular report in rows/column format in print. So I suggest to take it up next week as enhancement.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

From: MAGO, Sumit
Sent: Thursday, March 10, 2016 10:47 AM
To: 'OUPMATH/OxfordMath_UAT'; OUPMATH/OxfordMath_UAT
Subject: RE: [OxfordMath_UAT] Class performance print - usability issue (#128)

Hi,
               As we agreed during FSD to print report as shown on screen, let’s agree on improving report print output as discussed with Subha (increase no. of records in print output) and do it later in support period. Please place it under enhancement to be done in support.

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by sumitmago** [comment]
@manasghosh81, please mark it as enhancement to be closed during warranty period

**Comment by mayank2k2** [comment]
@manasghosh81 , My suggestion is to implement in similar fashion as we implemented for exports all records for promotion, if not possible then suggest possible solution.

**Comment by kirti-sharma** [comment]
Fixed.
