### ISSUE TITLE
Mandatory fields in bulk user upload excel not identified.

### ISSUE THREAD

**Issue by somabanerjee** [OUPMATH/OxfordMath_UAT#13]
Login as OUP admin. 
Created school. 
Downloaded template for uploading user data. 
Unable to identify the mandatory fields.

**Comment by manasghosh81** [comment]
This is not a valid defect.As per FSD user should go through the instruction sheet first and then fill the Sheet for student and teacher.In Instruction sheet is the first tab it is clearly mentioned what  are the required fields for Teacher and Studen

**Comment by somabanerjee** [comment]
Please modify the instruction sheet to capture this information about mandatory and optional fields in the Excel sheet. That's all we are asking for. In the  first tab it is not clear, which fields are mandatory, for example, the username which is the first field in the second sheet is needed only in case of an update, whereas this is a required field as per the instruction tab. The instructions are not very clear and precise. That is what needs to be fixed.

**Comment by mayank2k2** [comment]
Please discuss with soma and include me to figure out the way, we can highlight with different color for required columns in sheet.

**Comment by manasghosh81** [comment]
Hi Mayank, 
This is Subha. I have sent the excel to Soma, however didn't hear from her yet.

**Comment by mayank2k2** [comment]
Subha  soma is out this week you will get response in next week, 
Soma, please take action, my suggestion is to have different background eg yellow for mandatory columns in excel. Please provide your comment.

**Comment by madhumitadey** [comment]
Hi everyone, we have just sent a mail to Manas regarding the bulk upload excel sheet. The same has been finalized after discussion with Soma.

**Comment by mouparnadas** [comment]
The bulk upload excel updated.

**Comment by madhumitadey** [comment]
Okay
