### ISSUE TITLE
Home page Advance Search back button functionality

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#130]
Login as OUP admin/school admin/teacher.
Click on Advance Search.
Do any random search and go to page 2 of the student/teacher results.
![image](https://cloud.githubusercontent.com/assets/16831643/13628114/6368998c-e5f5-11e5-9b63-cde01a8e6b91.png)

Click on any one edit icon against one student/teacher.
Now click on back button.

Present functionality: User is redirected to fresh fresh search page.
![image](https://cloud.githubusercontent.com/assets/16831643/13628101/47cc2676-e5f5-11e5-9302-76e83f75383f.png)

Required functionality: The page should move back 1 step, e.g. to the page 2 search results in the current case.

**Comment by manasghosh81** [comment]
As discuss with Mayank,We should keep this open.
We should identify different possible solution and discuss with Mayank.

**Comment by kirti-sharma** [comment]
Fixed.
