### ISSUE TITLE
Bulk upload page case correction

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#132]
Login as OUP admin.
Search a school and go to its bulk upload page.
Do the following correction.

![image](https://cloud.githubusercontent.com/assets/16831643/13629235/ccc5e7e2-e5fd-11e5-94bb-cc177d7bd467.png)

**Comment by mouparnadas** [comment]
This is now fixed in UAT. Please review and close

**Comment by kirti-sharma** [comment]
Fixed.
