### ISSUE TITLE
Search results default view.

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#133]
Login as OUP admin/school admin /teacher.
Do any random search operation.
Present functionality: A list of 'All Records' within the search criteria is shown.
Required functionality: By default, 'Active Records' should be the search criteria.
![image](https://cloud.githubusercontent.com/assets/16831643/13630098/4fd7c060-e603-11e5-977b-251889791fd2.png)

**Comment by manasghosh81** [comment]
@mayank2k2 

As discussed with You by default "Active Records" will be selected.If user clicks the reset button then again all Record will be available.

We have done changes as discussed anad it is available in UAT

**Comment by kirti-sharma** [comment]
@mayank2k2 Can we close this issue now? I have checked and functionality is now as per the above comment by Manas.

**Comment by mayank2k2** [comment]
Please close it

Sent from Samsung Mobile

-------- Original message --------
From: kirti-sharma
Date:11/03/2016 22:13 (GMT+05:30)
To: OUPMATH/OxfordMath_UAT
Cc: "MISHRA, Mayank"
Subject: Re: [OxfordMath_UAT] Search results default view. (#133)

@mayank2k2https://github.com/mayank2k2 Can we close this issue now? I have checked and functionality is now as per the above comment by Manas.

**Comment by kirti-sharma** [comment]
Thanks. Fixed.
