### ISSUE TITLE
Alert message document requirement

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#135]
In the email dated 3rd March to Mouparna Das , a reminder of which was given on 8th March to Manas, we had asked a document containing alert messages for editorial review. We cannot close alert/popup message corrections issues without them and we can't find all such alerts/popups that need corrections.
#49

Also, we had shared bulk upload error message corrected sheet with TCS but even now we can see discrepancies in the messages. 
[Error.Messages.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/165007/Error.Messages.xlsx)

Kindly address these concerns

**Comment by sumitmago** [comment]
Hi,
I thought this is closed but basis my discussion with Soma, it seems there are still messages which are yet to be closed. Could we get them closed at priority?

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by somabanerjee** [comment]
@sumitmago It is only the bulk upload error messages that we have received, fixed and sent to TCS. For the other pop-ups, display messages, etc. we had requested a consolidated sheet from TCS, which we are yet to receive. We are making textual fixes to whatever we spot but without a consolidated sheet, we can't be sure that all errors/typos have been weeded out.

**Comment by sumitmago** [comment]
@TCS, my understanding was that entire error messages, notification etc. have been sent for screening. But I hear a different voice here. Could you please comment and if not sent, could you please immediately send the complete file please?

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by manasghosh81** [comment]
@kirti-sharma :I have sent you the consolidated list of all messages(notifications,Error,Bulk upload).

**Comment by kirti-sharma** [comment]
@manasghosh81 The updated excel has been shared with you over mail.

**Comment by mayank2k2** [comment]
@kirti-sharma can you take a look and take action

**Comment by kirti-sharma** [comment]
Fixed.
