### ISSUE TITLE
Report formats---incomplete printouts and blank pages

### ISSUE THREAD

**Issue by somabanerjee** [OUPMATH/OxfordMath_UAT#136]
This is regarding the printouts of Student Performance Reports. After a student has completed more than four tasks in a chapter, anyone viewing the report can use the left-right arrows to view performance in individual tasks. However, when the same report is printed, only the tiles on the screen get printed. Please see the two following PDFs as samples. 

[PerformanceReport (2).pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/166515/PerformanceReport.2.pdf)
[PerformanceReport (4).pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/166516/PerformanceReport.4.pdf)

My understanding was that  the printout of the report is a printout of the complete performance report, not just what is visible on the screen. This version is quite sad and no teacher will ever take multiple printouts to view a student's performance report.  Further on each page, only two rows of tiles are being printed and the rest of the page is blank.It looks as if something is missing. Please see what can be done to improve this.

**Comment by manasghosh81** [comment]
Hi Soma,
This functionality has already implemented. Could you please clear your browser cache and try again. I have also re-check the same thing in UAT with the below credential
Username: Student5
Password: OUPMath@769 
Please find the attached pdf sample
[PerformanceReport_only_one_section.pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/166761/PerformanceReport_only_one_section.pdf)
[PerformanceReport_full page.pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/166762/PerformanceReport_full.page.pdf)

**Comment by somabanerjee** [comment]
@manasghosh81 I just tried it again from a teacher login (after clearing my browser cache, as advised by you). I still see the same problem. 

[PerformanceReport (10).pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/167080/PerformanceReport.10.pdf)

The section print is fine, though.

**Comment by mayank2k2** [comment]
Please review and take action

**Comment by kirti-sharma** [comment]
A fresh downloaded report is enclosed. There are three concerns we wish to raise:
1. Although are assets are displaying now, assets on page 2 are overlapping.
[PerformanceReport (20).pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/168606/PerformanceReport.20.pdf)

2.Text on printout is going out of bounds.
[Scan of printout.pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/168608/Scan.of.printout.pdf)

3.As regards clearing cache, it is not a fair expectation from the user to clear the system cache every time before printing. Please provide support to further improve this functionality.

**Comment by manasghosh81** [comment]
Please recheck this .

**Comment by sumitmago** [comment]
@manasghosh81 please defer this for enhancement

**Comment by kirti-sharma** [comment]
Hi! This is Soma. If this is an enhancement, I think we can leave the issue open for the time being. We just tried downloading and checking any progress on this issue. Things are where they were a few weeks ago. I am not in favour of closing this issue. Lets tag it as enhancement and leave it at that. Frankly, no user will clear their cache each time before taking printouts of reports.

**Comment by mayank2k2** [comment]
@manasghosh81 what you have fixed ???

**Comment by mayank2k2** [comment]
@manasghosh81 , please discuss with your team and try to resolve

**Comment by mayank2k2** [comment]
@manasghosh81 , any update ??
