### ISSUE TITLE
Global capitalisation of first letter d in * denotes mandatory fields

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#142]
This is a global text change.
Capitalise the first letter D in the phrase ' \* **d**enotes mandatory fields ' .

Below are a couple of instances.
Login as teacher.
Go to create task/activity page.
Mark the following changes:
![image](https://cloud.githubusercontent.com/assets/16831643/13662287/5c2d2e74-e6bf-11e5-8b28-06a122ae7752.png)
![image](https://cloud.githubusercontent.com/assets/16831643/13662299/717a960e-e6bf-11e5-8329-59605158ed4f.png)

**Comment by somabanerjee** [comment]
Please close the space between the asterisk and the word.

**Comment by kirti-sharma** [comment]
Fixed.
