### ISSUE TITLE
Section-wise Comparison Report issue

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#145]
Steps:
1. Login using the following School admin credentials:
    Username: S3_5
    Password: OUPMath@218
1. Go to reports.
2. Select Class, Section and Chapters.

In the reports generated we have found the following issues:

The axis label for the y-axis is missing in both the graphs. It is not clear as to what the graphs show. This needs to be addressed. The position of the legend is not correct in the second graph.  Right now, it is getting lost between the labels. Move it to the bottom right-hand corner. The font size is also pretty small. It needs to be increased. A few textual corrections also needed. We have marked changes in the pdf attached.

Section-wise Comparison Report.pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/166843/Section-wise.Comparison.Report.pdf)

Please make the changes as suggested. In case of queries, please get back to us.

**Comment by manasghosh81** [comment]
We have fixed all the items except that are marked in red as attached in the following image

![school admin report](https://cloud.githubusercontent.com/assets/12447431/13701653/656d1a9e-e7af-11e5-91a0-cb3590478b24.png)

**Comment by sumitmago** [comment]
@manasghosh81 , most of the things are fixed but please increase legend font size to make it stand out. If need, then place it at the bottom of the paragraph.

**Comment by madhumitadey** [comment]
The legends of section-wise comparison report looks shabby.
![image](https://cloud.githubusercontent.com/assets/16831474/13708623/a7e72538-e7d5-11e5-8d5c-58a5ec873f10.png)

KIndly correct it as per the screenshot shown below.
![image](https://cloud.githubusercontent.com/assets/16831474/13708539/2917b8b2-e7d5-11e5-9b91-023c21c1f823.png)
If the term "section" can't be included, in that case, kindly shift the position of the legends as indicated and increase font size to make it readable.

Can close the issue once this is fixed.

**Comment by madhumitadey** [comment]
okay
