### ISSUE TITLE
Class performance report not generated correctly

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#149]
Login using Teacher credentials.
Go to reports page.
Go to class performance report.

The Chapter-wise Score Report and Task-wise Score Report is not generated correctly.

For example see the screenshot below. Here, the Task-wise average scores of the two tasks are shown.
![image](https://cloud.githubusercontent.com/assets/16831474/13667492/a06e2648-e6dc-11e5-89f6-46d601185197.png)

Now, the Chapter-wise score of this task is calculated by adding the scores of individual tasks in the numerator (i.e., 0+1 = 1) and total score of tasks in the denominators (10+24=34), and the score is displayed as 1/34 (see screenshot below). **This is logically incorrect.**

![image](https://cloud.githubusercontent.com/assets/16831474/13667574/0d87fef2-e6dd-11e5-903d-ae7e0e3e3c43.png)

As per the FSD (Pg 94-97), the Task-wise average scores of all tasks should be converted to percentages. **Then the average of the percentages of all tasks should be calculated and displayed in the Chapter-wise Score Report.** Therefore, the second column of Chapter-wise Score Report is invalid (as the calculation is logically incorrect) and should be deleted.

**Comment by manasghosh81** [comment]
@madhumitadey : We believe that calculating chapterwise avg percentage as a mean of the task average percentage is wrong. Please check some sample data in the attached excel. 
If you take Chapter 01 in the attached excel, there are 2 tasks, place value and even & odd numbers.

## Here are the scores

Subha Dey1: Place value = 8/15
Subha Dey1: Even & odd = 8/10

Subha Dey2: Place value = 11/15
Subha Dey2: Even & odd = 6/10

Subha Dey3: Place value = 4/15
Subha Dey3: Even & odd = 10/10

Thus Average task wise:
- Place value = (total of all task scores)/(number of students) = (8+11+4)/3 = 8 (rounded)
- Even & odd = (total of all task scores)/(number of students) = (8+6+10)/3 = 8 (rounded)

Thus Average % task wise:
- Place value = average / full marks = 8/15= 53%
- Even & odd = average / full marks = 8/10 = 80%

Now you are saying chapterwise average (%) should be calculated as the mean of above percentage which means (53+80)/2 % = 67% 
This translates to absolute score of 67% of (full marks for chapter) = 0.67X25 = 17 (rounded)
Thus with 3 students, total marks obtained in chapter = 17X3 = 51

But in reality the students have obtained total marks for the chapter as (8+8+11+6+4+10) = 47

So the average chapter score calculation should be (total marks obtained by all students for all tasks in the chapter) / (total number of students) and the percentage should be calculated as (this average score) / (full marks in the chapter)

[Average TEsting_v1.0.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/167740/Average.TEsting_v1.0.xlsx)

**Comment by mayank2k2** [comment]
@manasghosh81 please directly discuss with soma and sort out the calculation logic

**Comment by manasghosh81** [comment]
@mayank2k2 : I have written the logic above. I am not feeling well today, would be great if Soma/you can call me so that we can discuss. Probably the text I have written is self explanatory.

Regards
Subha

**Comment by sumitmago** [comment]
Dear Soma,
               Could I request you to please read the logic given by Subha and revert asap on #49
Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by mayank2k2** [comment]
@somabanerjee , please discuss with subha about required logic.

**Comment by somabanerjee** [comment]
This issue needs to be discussed internally to arrive at a consensus before TCS makes any changes in the implementation. For the time being this stands deferred.

**Comment by mayank2k2** [comment]
@somabanerjee , @sumitmago we need to discuss the performance report calculation logic internally that need to be implemented/changed.

**Comment by mayank2k2** [comment]
@somabanerjee , as per yesterday discussion. pleas revert on this.

**Comment by mayank2k2** [comment]
@somabanerjee , reminder! please suggest by what logic we should go ahead.

**Comment by sumitmago** [comment]
Dear Soma,
               Last time, we spoke and agreed that a final consideration would be given and then we can conclude which average method to use. So could I request you to please confirm on this so that we communicate to TCS and resolve this average issue

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve
