### ISSUE TITLE
Number of homework attempts - functionality

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#150]
Login as student.
Attempt homework of any assigned task.

Query: If I close the homework after attempting only one of the two questions, will  my number of attempts counter increase? 
I am not sure how is this working. Please clarify!

**Comment by manasghosh81** [comment]
@kirti-sharma : Unless and until you mark both questions as complete checkout within the homework, it is not recording it as an attempt - that's what we saw in UAT
