### ISSUE TITLE
Display message "*Denotes mandatory fields" should appear on the pages where red asterisks appear

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#151]
There should be a display message stating "*Denotes mandatory fields" on the pages where red asterisks appear.

A few instances are captured here for your reference. However, we have not capture all instances here. Kindly make this change globally.

Login using Teacher credentials.
Go to reports.

![image](https://cloud.githubusercontent.com/assets/16831474/13695465/26e651ca-e785-11e5-80b6-8da11519bc3f.png)

![image](https://cloud.githubusercontent.com/assets/16831474/13695471/2e53c208-e785-11e5-8c18-b1aa06de7c52.png)

Login using School admin credentials.
Go to classes-->create new teacher

![image](https://cloud.githubusercontent.com/assets/16831474/13695562/028d79ec-e786-11e5-92a7-8c1f299b5dfb.png)

**Comment by mayank2k2** [comment]
this is not looks good

![image](https://cloud.githubusercontent.com/assets/16239450/13701229/7d1a8bd4-e7ac-11e5-9288-0a7b9d18b4ae.png)

**Comment by manasghosh81** [comment]
Please clear the cache or Press ctrl+F5.I am able see proper image
![school admin](https://cloud.githubusercontent.com/assets/12447431/13701358/5945f274-e7ad-11e5-936c-e606b2f44acc.png)

**Comment by madhumitadey** [comment]
Looks good.
