### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#153]
@manasghosh81 

The final XML files are kept at the following location: 
ftp://ftp.oup.co.in/OM%20files%20for%20upload_20%20May/ 

There are 13 files in the folder. 
[Validation_issues_16_May[1].xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/276802/Validation_issues_16_May.1.xlsx)

**Comment by manasghosh81** [comment]
@madhumitadey,
Could you please close this issue in and raise in Prod -Repository  instead of UAT repository.
We are not tracking this repository at all.
mayank2k2,
Please help Madhumita to raise the issue in proper repository.

**Comment by madhumitadey** [comment]
Done
