### ISSUE TITLE
UAT - School admin licence will expire on 31/12/2016 - Need renewal

### ISSUE THREAD

**Issue by Kaushik58** [OUPMATH/OxfordMath_UAT#155]
**UAT - School admin licence will expire on 31/12/2016 - Need renewal**
URL - http://www.uat.oxfordmaths.co.in
User ID - S62_4752

Regards,
Kaushik

**Comment by mayank2k2** [comment]
please log in https://github.com/OUPMATH/OxfrodMaths_Prod/issues
and assign to Vrinda
