### ISSUE TITLE
Incorrect UAT student credential for Oxford Maths

### ISSUE THREAD

**Issue by Kaushik58** [OUPMATH/OxfordMath_UAT#156]
We have received the credentials for Oxford Maths both for UAT and Production, 
We tried to login with those credentials and only the UAT student credential is not working, 
So raising the ticket here as per Mayank's instruction.

UAT Student userid: STUDENTCOGNIZANT

Could you please look into it ASAP.

**Comment by mayank2k2** [comment]
Hi This portal is no more in use.
Please raise issues into below github url
https://github.com/OUPMATH/OxfrodMaths_Prod/issues
if any issue related to UAT, make subject starting with UAT:…

Thanks,
Mayank Mishra
