### ISSUE TITLE
School logo not correct in the welcome letter

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#16]
Steps to reach the page:
1. Login to School Admin
2. Visit Utilities Tab
3. Download multiple welcome letters by selecting multiple students under 'Student search histort'.

Error: The Oxford logos (on the top right corner) on the second and the third pages of the welcome letter are incorrect. Insert 'Oxford School Education Logo'. Adjust the size of the logo so that the image doesn't appear squeezed or spread out.

[WelComeLetter (3).pdf](https://github.com/OUPMATH/OxfordMath_UAT/files/118709/WelComeLetter.3.pdf)

**Comment by manasghosh81** [comment]
This issue has been fixed and will be available in next deployment

**Comment by manasghosh81** [comment]
This is fixed now and available in UAT for retest
