### ISSUE TITLE
Functionality to select dates

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#18]
Steps 
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Select the "Academic session start", "Academic end date", “Subscription Start Date”, and “Subscription End Date” field

Present functionality
In the "Academic session start", "Academic end date", “Subscription Start Date”, and “Subscription End Date” fields, user is able to browse through months to select date.

Requirement:
Users should be able to browse through years as well as months while selecting the dates.

**Comment by manasghosh81** [comment]
Double click on the month name to browse through all the months.
Similarly on the year to browse through years.
