### ISSUE TITLE
Notification message not displayed on inputting alphanumeric pincode

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#19]
Steps
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Check the Address detail section
Try to fill the pin-code field with alphabets or alphanumeric characters

Present functionality
On trying to register the school with wrong pin-code, the field gets highlighted with Red.

Required functionality
It should not take the characters and an error message should be thrown to input proper numeric characters in the field.

**Comment by kirti-sharma** [comment]
In addition to the above issue, please note the following also:

Present functionality
On trying to register the school with less than six digits pincode, school details are updating successfully.

Required functionality
The field should be highlighted in red and the page should not get updated.
