### ISSUE TITLE
Notification message not displayed on not inputting class code

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#20]
Steps
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Check the Class wise subscription section
Click on the Class Code field
Choose the “Select class’ option in the drop down menu

Present functionality
On trying to register class with the "Select class" option, the field gets highlighted in red to show the error

Required functionality
If user does not select any class under class code and tries to save data, error message should be thrown as “Class code is mandatory” and the filed should get highlighted.

**Comment by mayank2k2** [comment]
Reviewed , Please put a generic required validation message at top of page.

**Comment by madhumitadey** [comment]
As requested, the message is not displayed.

If user does not select any class under class code and tries to save data, error message should be thrown as “Class code is mandatory.” and the filed should get highlighted.

**Comment by mouparnadas** [comment]
The messaging has been implemented.
