### ISSUE TITLE
Pop up message not disappearing after correct value has been entered

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#21]
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Enter data in all the fields.
Enter first field as "XYZ School". Click on register button. 
Message received is "School name already registered."

Enter a different school name and delete "address line 1".
Click on register button.

Present Functionality
The pop up message "School name already registered." remains on the screen even when the error is corrected.
Required functionality
The message should vanish when the requirements of the fields are fulfilled.

Note: Similar issues are found in other fields as well. Please correct the issue for incorrect entries in all the other fields of this page.

**Comment by manasghosh81** [comment]
This is not a defect. If there are any validation messages it will only disappear when user clicks on any button and the action goes to the back end to re-validate the values in the form.

**Comment by mayank2k2** [comment]
this is not valid scenerio
