### ISSUE TITLE
Error message not displayed when address fields are not inserted

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#22]
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Check the Address detail section
Fill all the mandatory fields of School register page except Address Line1, Country, State and Pincode from Address section and try to save the data

Current functionality
Error fields get highlighted in red

Required functionality
It should throw an error message and should highlight the fields with Red.

**Comment by manasghosh81** [comment]
This is a usability issue.we will fix it

**Comment by madhumitadey** [comment]
Notification message still not appearing, as suggested previously.

**Comment by mouparnadas** [comment]
The issues have not yet been fixed. Once fixed we will assign them and mark as fixed.

**Comment by madhumitadey** [comment]
Though the field gets highlighted in red, no notification error is being displayed.

**Comment by mouparnadas** [comment]
Messaging has been added.
