### ISSUE TITLE
Contact field not being highlighted 

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#23]
Steps
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Check the School Admin Details Section
Fill all the mandatory fields of the School register page except First Name, Last Name, Gender, Email and Contact of the School Admin Details section and Click on register button

Current functionality
The respective fields gets highlighted in red and the user is prompted to fill those fields

Error:
Contact field  listed above is not being highlighted

**Comment by mayank2k2** [comment]
Manas can you put the screen shot of FSD also.
