### ISSUE TITLE
Error message not displayed when email field not inserted

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#24]
Steps
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Check the School Admin Details Section
Fill all the details of the page with correct data except for email field. Either input a wrong email id format or keep the field blank and try to save the data

Current functionality
The email field gets highlighted in red and the user is being prompted to fill those fields.

Error:
An error message should be thrown stating either “Please enter a valid email address.”

**Comment by manasghosh81** [comment]
This will be an usability issue,we will fix it

**Comment by madhumitadey** [comment]
Error notification message not displayed, as suggested.

**Comment by mouparnadas** [comment]
The issues have not yet been fixed. Once fixed we will assign them and mark as fixed.

**Comment by madhumitadey** [comment]
Error notification message not displayed, as suggested. Only the field gets highlighted in red.

**Comment by mouparnadas** [comment]
The message has been added.
