### ISSUE TITLE
No message thrown when alphanumeric character is entered in contact field

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#25]
Steps
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Check the School Admin Details Section
Try to input alphabets or special characters in the contact field

Current functionality
Though the contact field gets highlighted in red, school gets registered.

Error:
_School should not get registered. An error message should be thrown asking the user to input valid numeric characters and the field should be highlighted._

**Comment by manasghosh81** [comment]
This is similar usability defect,we will fix it

**Comment by madhumitadey** [comment]
Though the field gets highlighted in red, no notification error is being displayed.

**Comment by mayank2k2** [comment]
Put the valid regex.

**Comment by madhumitadey** [comment]
Though the field gets highlighted in red, no notification error is being displayed.

**Comment by mouparnadas** [comment]
Rule changed as per issue #60 raised by Kapil Tuli. Right now it will accept only 12 digits or less
