### ISSUE TITLE
Duplicate email ID of school admin accepted

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#26]
Steps
Log on into the application with a valid OUP admin credential.
Click on the Register School Option
Check the School Admin Details Section
In the email field try to input an email id of already existing School Admin and try to save the data

Current functionality
Multiple schools are registered using the same ID, no error pops up.

Error:
It should throw an error stating that the email id already exists.

**Comment by manasghosh81** [comment]
Email field for School admin whatever we are capturing  is not used as authentication.This is captured
as non-unique in database as per the FSD.

**Comment by mayank2k2** [comment]
Hi Soma, Can you suggest on this. do we need to check duplicate email id for school admin.

**Comment by somabanerjee** [comment]
@mayank2k2     Although non-unique, but system should not permit same email id to be used for more than one school admin. Should throw a pop up cautioning the user.

**Comment by madhumitadey** [comment]
Same email ID can still be used to create a new school admin. This issue has not been fixed.

**Comment by manasghosh81** [comment]
@mayank2k2 - This is Subha. We are not doing it now. This has got some work to do at the backend validation side and we need to make the email column indexed and put these validation.

**Comment by mayank2k2** [comment]
Soma, can you also assign severity lebel it "high", "critical" or "low"

**Comment by manasghosh81** [comment]
As discussed in defect triage, this will be taken care of later and will request Soma to discuss with Sumit.
