### ISSUE TITLE
Login: OUPI Admin Login Issue

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#3]
Step 1: Go to the Orford math url link 
Step 2: Provide  User Id and Password for Oupi admin user 
Step 3: Click on Login button

Issue: User is not able to log-in 
Expected Reult: user should be log-in into the system and Amin dashboard should be displayed.

**Comment by manasghosh81** [comment]
This issue is fixed now after the change of settings in AWS by Jitendra

**Comment by edleung** [comment]
Test

**Comment by mayank2k2** [comment]
Now it is working
