### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#30]
Steps:
Log on into the application as School Admin and open the “My school Profile”
Try to update some values on the school profile page
Try to update some value and click on the save button
A message stating that “.. has been updated successfully” should be thrown

Present functionality: Following alert is received-
"School details has been updated successfully! "

Required functionality: Correct the alert to- 
"School details have been updated successfully! "

**Comment by manasghosh81** [comment]
The sentence has been corrected and will be available in next deployment
