### ISSUE TITLE
Teacher Role not displayed on profile page

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#32]
Step:
Open the OUP my maths url in a browser
Provide the school admin login credential and click on login.
Fill First Name or Last name with a valid existing Teacher's details and click on Search
Click on the edit button of the Action column
Try to update and save the profile

Present functionality: Role is not visible on the profile page
Required functionality: School Admin should be able to update and save all the fields except for username, profile pic and the role

**Comment by mouparnadas** [comment]
The issue has been fixed. Now the Username and Role will be visible. The change will be available in next deployment.
