### ISSUE TITLE
Role, roll # and password not displayed on profile page

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#33]
Steps:
Open the OUP my maths url in a browser
Provide the school admin login credential and click on login.
Fill First Name or Last name with a valid existing Student's details and click on Search
Click on the edit button of the Action column
Try to update and save the profile

Present functionality: Functionality is correct but Role, roll number and password are not displayed on profile page
Required functionality: School Admin should be able to update and save all the fields except for username, profile pic and the role, roll number and password

**Comment by mouparnadas** [comment]
The Username, Role and Roll number will be displayed.
But the password will not be displayed

**Comment by mouparnadas** [comment]
This has been fixed and will be available in next deployment.
