### ISSUE TITLE
Change atleast to at least

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#34]
Steps:
1 Open the OUP my maths url in a browser
2 Provide the school admin login credential and click on login.
3 Click on the advance search button against the (User can do basic search too)
4 Provide some valid search criteria and click on search
5 Check the action column for both teachers and students
6 Uncheck all records for teacher and click on button 'Deactivate selected'.

Present functionality: In step 6, following alert pops up-
Please select atleast one user.

Required functionality: Modify alert to-
Please select at least one user.

**Comment by manasghosh81** [comment]
The alert has been updated and will be available in next deployment
