### ISSUE TITLE
Test case for warning required

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#35]
Steps 
Log on into the application with a valid OUP admin credential.
Click on the School Search
Do a search on basis of any search field
Click on the send upload icon against a school under the action column
Click on the browse button and click on validate
Verify the status column under the generated grid

Current functionality
It should show three values based on the upload status. It should show error present if there is some error in the uploaded sheet. No error if no error is there in the sheet and warning present if some warnings are there and not errors.

Requirement
Test case to check warning present if some warnings are there and not errors required

**Comment by mouparnadas** [comment]
Point to FSD where Bulk Upload excel cases are mentioned under create user section.
