### ISSUE TITLE
Cannot download an uploaded data excel file

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#36]
Steps 
Log on into the application with a valid OUP admin credential.
Click on the School Search
Do a search on basis of any search field
Click on the send upload icon against a school under the action column
Click on the browse button and click on validate
Click on the file name hyperlink
Error:
Currently, on clicking the link to download an uploaded file, user gets redirected to the following error page
http://oup-mymath-elb-2074067178.ap-southeast-1.elb.amazonaws.com/User/DownloadFile?fileName=52c497bb-6668-425d-a590-3f40fef91888_Upload_User_Template_V1.0_G4.xlsx 

Required functionality
It should enable user to download the original uploaded file

**Comment by mouparnadas** [comment]
The issue will be fixed later.
