### ISSUE TITLE
Email id of school admin should be mandatory

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#37]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the school admin login credential and click on login.
Step 3      Click on the name link of the user at the top right corner
Step 4      Delete email of school admin on this profile page.
Step 5      Click on save.

Present functionality: Profile of school admin is getting updated without email id.
Error: Email of school admin should be mandatory field.   

.

**Comment by manasghosh81** [comment]
Email of school admin has been made mandatory field. The changes will reflect in next deployment.
