### ISSUE TITLE
Error message not displayed when more than 100 char are inserted in subject field

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#38]
Steps 
Log on into the application with a valid OUP admin credential.
Click on the Create notification link
Check the Subject field
Keeping this field blank try to send / schedule a notification
Try to input more than 100 characters to the field and save data
Error:
The error message is not thrown as required.

Required functionality
An error message should be thrown as the field length should be <=100.

**Comment by mayank2k2** [comment]
Please validate

**Comment by mayank2k2** [comment]
This is not valid defect
