### ISSUE TITLE
Correction in pop up message

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#39]
Step 1  Log on into the application with a valid OUP admin credential.
Step 2  Click on the School Search
Step 3  Do a search on basis of any search field
Step 4  Check the Action Column
Step 5      Click on 'Resend Welcome Email' icon

Present functionality:       Message received 'Email has been send successfully.'
Required functionality:     Modify message to 'Email has been sent successfully.'

**Comment by mouparnadas** [comment]
The message has been updated and it will reflect in next deployment.
