### ISSUE TITLE
Search: Hitting Search Open Advance Search unfront

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#4]
Step 1: Login to Admin user go to dash-board page
Step 2: Put "test" value in first name and hit search, 
Issue: It open the advance search dialog

Expected: It should not open advance search automatically

**Comment by manasghosh81** [comment]
This is working as per FSD.

**Comment by mayank2k2** [comment]
This also an usability issue

**Comment by mayank2k2** [comment]
this is issue

**Comment by manasghosh81** [comment]
As discussed in our defect triage meeting this will be decided later

**Comment by mayank2k2** [comment]
closing this issue as of now, if someone else report this later we will reopen
