### ISSUE TITLE
Error message not displayed when more characters are inserted in message notification field

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#40]
Steps 
Log on into the application with a valid OUP admin credential.
Click on the Create notification link
Check the Message field
Keeping this field blank try to send / schedule a notification
Try to input more than 500 characters to the field and save data

Error:
The error message is not thrown as required. Also, the system takes only 300 words as input.

Required functionality
An error message should be thrown as the field length should be <=500. 
The system should be able to take 500 characters.
There should be a letter counter beside the subject and message field to keep a track of number of letters

**Comment by mayank2k2** [comment]
• Notification subject will have a max limit of 100 characters
• Notification Message will have a max limit of 500 characters

**Comment by manasghosh81** [comment]
No message since user cannot enter more than 300 number of characters as per FSD and Datamodel. Character counter is an enhancement

**Comment by mayank2k2** [comment]
This is bug and The system should be able to take 500 characters.

**Comment by mouparnadas** [comment]
The word limits have been updated to 500.

**Comment by madhumitadey** [comment]
Although, now the system takes 500 characters, still the notification couldn't be created. 

![error charater input](https://cloud.githubusercontent.com/assets/16831474/13073328/157d7c34-d4c4-11e5-96f8-2686d315dd08.png)

**Comment by mouparnadas** [comment]
Please retest.

**Comment by madhumitadey** [comment]
This is working fine now.
