### ISSUE TITLE
Password not getting updated in welcome letter

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#41]
Step 1  Open the OUP my maths url in a browser  It should open the OUP mymaths homepage successfully.
Step 2  Provide the school admin login credential and click on login.   User should be able to open the school admin home screen successfully.
Step 3  Click on the utilities link from dashboard or side bar  User should be redirected to utilities page. School name and school code should not be an option in the search criteria
Step 4  Search for a record Student and teacher's details should be generated in two different grids .
Step 5  Check the action column of the search grid  It should contain export and print welcome letter options
Step 6  Click on print welcome letter option    It should generate a pdf file. If multiple users are selected then the generated pdf should be a single file with separate page for each user

Present functionality: The passwords on welcome letter are reset to the old temporary passwords.

Required functionality: Generate new temporary passwords.
Also, change "This will generate temp new password and student/teacher won’t be able to use old password if any"  to

"This will generate a new temporary password and student/teacher won’t be able to use old password, if any.  "

**Comment by mouparnadas** [comment]
During print of welcome letter, if the password of the user is temporary (i.e user has not yet logged for the first time), the same password will be printed on the welcome letter. If the password is not temporary, the process will reset the password and the new temporary password will be printed in the welcome letter

**Comment by kirti-sharma** [comment]
Present functionality: The passwords on welcome letter are reset to the old temporary passwords.

Required functionality: Generate new temporary passwords.
Also, change "This will generate temp new password and student/teacher won’t be able to use old password if any" to

"This will generate a new temporary password and student/teacher won’t be able to use old password, if any. "

**Comment by kirti-sharma** [comment]
Present alert: This will generate temp new password and student/teacher won’t be able to use old password if any
Required alert: This will generate a new temporary password and student/teacher won’t be able to use old password, if any. 

Refer to screenshot below:
![temp password](https://cloud.githubusercontent.com/assets/16831643/13072060/4256b524-d4bd-11e5-8667-4dbad6054758.png)

**Comment by kirti-sharma** [comment]
Can't see the suggested change on retest.

**Comment by kirti-sharma** [comment]
The text in the warning has not been corrected.
![image](https://cloud.githubusercontent.com/assets/16831643/13210167/6a56abda-d952-11e5-8d02-c3a01c54cdee.png)

**Comment by mouparnadas** [comment]
This is now fixed.
