### ISSUE TITLE
Make email mandatory in the OUP admin profile page

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#42]
Steps 
Log on into the application with a valid OUP admin credential.
Click on the hyperlink showing the user's name at the top right side
Check the personal details section
Check the Email Field
Make the field blank and try to update the data
Current functionality
User should be able to save the data.

Required functionality
Make email mandatory so that passwords can be retrieved and changed.

**Comment by manasghosh81** [comment]
The email has been made mandatory field. The changes will reflect in next deployment.
