### ISSUE TITLE
Correction i

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#43]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the school admin login credential and click on login.
Step 3  Click on the advance search button against the (User can do basic search too)
Step 4  Provide some valid search criteria and click on search
Step 5  Check the action column for both teachers and students
Step 6  Click on the delete icon against a teacher (User can do this for multiple records also by selecting the checkboxes and clicking on the link delete selected)

Present functionality: Following message pops up-
User(s) has been deactivated successfully!

Required functionality: Modify the sentence to-
User(s) deactivated successfully!

**Comment by manasghosh81** [comment]
The text has been updated and will be available in next deployment

**Comment by mayank2k2** [comment]
manas, please put proper comment.
