### ISSUE TITLE
Static text for OUPI Admin dash board is not same as the one given in test case 

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#44]
Refer attached word doc for details

[Test case conflict.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/121235/Test.case.conflict.docx)

**Comment by mouparnadas** [comment]
The text has been updated. Revised text is being used.

**Comment by mouparnadas** [comment]
Hi Subha, 

Here is the contracted text:

Welcome OUPI Admin! 
Manage schools and subscriptions smoothly. Generate log-in credentials, send notifications to schools, etc. 

Welcome School Admin! 
Manage your school profile and users.  Track and compare class performance, and create and send notifications with a single click! 

Welcome Teacher! 
Manage your classes--assign tasks, review the task completion status and track the performance of all your students.   

Welcome Student! 
Find all your resources, including lessons, practice questions, and games, here. Get instant scores and track your performance.

Hope this will be fine. 

Soma
