### ISSUE TITLE
Grammatical correction in error message

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#45]
Step 1  Log on into the application with a valid OUP admin credential.
Step 2  Click on the School Search
Step 3  Do a search on basis of any search field
Step 4  Click on the send upload icon against a school under the action column
Step 5  Click on the browse button and click on validate
Step 6  Verify the status column under the generated grid

Present functionality: If there is error in class code, the excel is displaying 'Error: Class code not exits'

Required functionality: Modify this sentence to 'Error: Class code does not exist. '

**Comment by mouparnadas** [comment]
The issue has been fixed this will be available in next deployment

**Comment by kirti-sharma** [comment]
Closed
