### ISSUE TITLE
Wrong notification message generated

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#46]
Steps
Log on into the application with a valid OUP admin credential.
Try to do a basic search or an advance search to view user details
Check the Action column for both teacher and student search grid
Click on the delete button
Check the action column again
Click on the activate/restore icon
This deactivate can be done for multiple records by selecting the check boxes and then clicking on the deactivate selected link

On selecting multiple records and trying to deactivate them, system pops up a message every time “Please select atleast one user.”
This message should not appear if users are already selected. It should appear only when no selection is done.

**Comment by mouparnadas** [comment]
The invalid pop up message has been fixed. The fix will be available in next deployment
