### ISSUE TITLE
Correction in pop up

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#47]
Step 1 Open the OUP my maths url in a browser
Step 2 Provide the school admin login credential and click on login.
Step 3 Click on the advance search button against the (User can do basic search too)
Step 4 Provide some valid search criteria and click on search
Step 5 Check the action column for both teachers and students
Step 6 Click on the delete icon against a teacher (User can do this for multiple records also by selecting the checkboxes and clicking on the link delete selected). Confirm deletion.
Step 7 Click on the Activate user icon. Confirm activation.

Present functionality: Following message pops up-
User(s) has been activated successfully!

Required functionality: Modify the sentence to-
User(s) activated successfully!

**Comment by mouparnadas** [comment]
The issue has been fixed and will be available in next deployment.
