### ISSUE TITLE
Advance search: Closing option missing

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#5]
Step 1: Login to Admin user go to dash-board page
Step 2: Click on Advance search link, It open the advance search dialog

Issue : there is no way to close the advance search dialog. 
Expected: It should have close option

**Comment by manasghosh81** [comment]
As per FSD this is the functionality. To close the advance search, OUP admin can click on the Dashboard link

**Comment by mayank2k2** [comment]
This is not enhancement and but usability issue

**Comment by mouparnadas** [comment]
The close option has been implemented.

**Comment by mayank2k2** [comment]
working fine
