### ISSUE TITLE
 OUP logo should open OUPI website

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#51]
Steps:
User to open a browser.
User should put the mymaths url and click on enter.
Click on the OUP logo at the bottom left side corner of the screen.

Present functionality: It is taking user to the top of the screen.
Required functionality: Oxford University Press India website should open in a new tab.

**Comment by mouparnadas** [comment]
The changes have been implemented. It will appear in next deployment.
