### ISSUE TITLE
Bulk Upload Performance issue

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#53]
I try to uploaded 2000 users, validation not getting completed,  status shows busy icon even after 15 minutes and continue, please see below attached.
![bulk upload issue](https://cloud.githubusercontent.com/assets/16239450/12938469/1fcf345a-cfda-11e5-96e0-6bd8d3e37e35.jpg)

**Comment by manasghosh81** [comment]
@Mayank:
Please create a new school and single class code with 2500 subscription count.Download the attached sample excel.Put 2000 students in the excel.Try to upload.

We have tested the above scenario.It is taking 10 mins approx.Please check this from your side

**Comment by manasghosh81** [comment]
TCS will do a quick test with 1000 users and record the time with screenshots.

**Comment by sumitmago** [comment]
And one with 500 would also be appreciated

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by manasghosh81** [comment]
As per the latest testing done, 1030 users were uploaded. The screenshot attached here shows the upload time and the processing finish time which we have captured.(Both the timings are highlighted in the screenshot)
![bulk2](https://cloud.githubusercontent.com/assets/12447431/13427118/e1c1e38e-dfd7-11e5-87ac-9387ac0008a6.png)
I am also attaching the file which I have uploaded.
[RealBulk_KVD.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/152757/RealBulk_KVD.xlsx)

**Comment by manasghosh81** [comment]
@mayank2k2 : pls check this and close it

**Comment by mayank2k2** [comment]
how it looks better
