### ISSUE TITLE
Security issue: School admin shouldn't allow any other school profile

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#55]
I logged in as School admin go to view school profile, 
not i have change the school id parameter on top i am able to see any other school profile.  

This is security issue and School admin shouldn't allow to view any other school profile.

**Comment by manasghosh81** [comment]
It will be available in next deployment

**Comment by mouparnadas** [comment]
The URL query encryption has been implemented

**Comment by mayank2k2** [comment]
Working fine
