### ISSUE TITLE
Conflicting screens appearing with same inputs.

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#56]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the school admin login credential and click on login.
Step 3  Click on the classes link
Step 4      Enter a class and click enter
Step 5      Click on Replace teacher icon against one row.

Present functionality: Two different screens are appearing with same inputs. please see attachment.
Please check the conflict.
![replace teacher search](https://cloud.githubusercontent.com/assets/16831643/12940058/73ad76c0-cfeb-11e5-8faf-6a542a5ec60a.png)

**Comment by mouparnadas** [comment]
This will populate the teacher list with the search criterion. The school admin will have an option to assign teacher other than selected teacher.

**Comment by kirti-sharma** [comment]
Please notice that, in both the screens of the screenshot shown, no value has been entered in any field before clicking on the search button. In the first screen, it is populating the list of all the teachers of that school; whereas in the other it is prompting the user to enter data in the first field (i.e, username).
So at different time instants, same search is giving two different outcomes.
