### ISSUE TITLE
Wrong tagging of 'Oxford Maths' top left logo on home page.

### ISSUE THREAD

**Issue by kapiltuli2016** [OUPMATH/OxfordMath_UAT#59]
Issue: Click on Oxford Maths 'top left' logo, takes visitor to OUPI website.
Expected result: Should always take visitor to the Oxford Math's home page, from any other section in the site.

**Comment by mouparnadas** [comment]
The change has been applied and will be available in next deployment.

**Comment by mouparnadas** [comment]
This is now working accordingly.
