### ISSUE TITLE
'No. of digits' rule missing in 'Contact' field in "Contact Us" page

### ISSUE THREAD

**Issue by kapiltuli2016** [OUPMATH/OxfordMath_UAT#60]
Issue: It allows submission with any no. of digits.
Expected result: Should not allow more than 12 digits(thereby allowing both mobile nos. and landline nos. with std codes)

**Comment by mouparnadas** [comment]
The change has been added. Made the digit count 12. This will be available in next deployment.

**Comment by manasghosh81** [comment]
This is fixed now available in QA,will be available in UAT after next deployment

**Comment by mouparnadas** [comment]
This is now working accordingly.
