### ISSUE TITLE
Contact us page corrections

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#61]
Please correct as marked in the screenshots.
![home page request form error](https://cloud.githubusercontent.com/assets/16831643/13000475/bd6b7ad2-d180-11e5-9ab5-04d02277c2a0.png)

![home page contact details error](https://cloud.githubusercontent.com/assets/16831643/13000367/894f6106-d17f-11e5-86f3-699e66260b57.png)

**Comment by mouparnadas** [comment]
The fix have been applied and the changes will reflect in next deployment.

**Comment by kirti-sharma** [comment]
Please see corrections on screenshot
![home page request form error](https://cloud.githubusercontent.com/assets/16831643/13071233/2225f54e-d4b8-11e5-9a55-15022b1d260e.png)

**Comment by mouparnadas** [comment]
The "input symbol" text modification have some technical challenges. 
As an alternative the part can be updated as below : 
![captcha](https://cloud.githubusercontent.com/assets/17062939/13082618/623b7ee4-d4f7-11e5-8617-78406dff7a75.JPG)
Please confirm if this is fine.

**Comment by kirti-sharma** [comment]
Yes, this is fine.
