### ISSUE TITLE
contact us page - Home page module

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfordMath_UAT#62]
1. contact text box must have some validation on the number of numeric characters that phone no can have. Phone no. validation was discussed with Subha. so please go by those.
2. There is no space between captcha label and captcha text box. please fix that.
3. if any mandatory field is left blank or if there is any other error, we must display the error at top and then highlight the text field. This is already agreed with Subha and Manas. please speak to them.
   ![contact us_phone no](https://cloud.githubusercontent.com/assets/13584396/13002407/3e8e1dbe-d194-11e5-90ef-26f12c0386f5.PNG)

**Comment by mouparnadas** [comment]
The changes have been implemented and will be available in next deployment.

**Comment by sumitmago** [comment]
This is fixed & closed.
