### ISSUE TITLE
contact us page - call center timings update

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfordMath_UAT#63]
hi,
   Please change the contact time hours and days in contact us page to 

24X7 Toll Free Support - 1800-4190-901 

![contact us - contact hours](https://cloud.githubusercontent.com/assets/13584396/13002845/a58a4bb6-d197-11e5-8841-fe067643aa93.PNG)

**Comment by mouparnadas** [comment]
The contact time hours and days in contact us page have been updated. The changes will appear in next deployment.

**Comment by mayank2k2** [comment]
Please review

**Comment by sumitmago** [comment]
This is fixed and closed
