### ISSUE TITLE
Press Enter key in First Name or Last Name should allow for default search

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#64]
Login with OUPI admin,
Enter some value in First Name or Last Name eg. "test" and hit Enter key
Issue: Nothing happen
Expected : Hitting enter key should allow default search bahaviour in this case.

**Comment by mouparnadas** [comment]
This is now working accordingly.

**Comment by mayank2k2** [comment]
working fine
