### ISSUE TITLE
Press Enter key in advance search text controls should allow for default search

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#65]
Login with OUPI admin,
click on advance search link 
Enter some value in any control eg. First Name, Last Name, Roll Number, .... and hit Enter key
Issue: Nothing happen
Expected : Hitting enter key should allow default search behavior.

**Comment by mouparnadas** [comment]
This is now working accordingly.

**Comment by mayank2k2** [comment]
working fine
