### ISSUE TITLE
Image control should allow only Images filter

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#66]
Login in with any user , go to profile page and click on "edit photo" it allow any file to select.

Issue: all the files are visible.
expected: only images should be visible as those are valid one for select and upload.

![image filter issue](https://cloud.githubusercontent.com/assets/16239450/13003641/ce5c87d4-d19c-11e5-8b2f-2be11c1f95e1.JPG)

**Comment by mouparnadas** [comment]
This is now handled. Now the filter will have options for all files and .png or .jpeg images.
If user try any other file type then error is shown

**Comment by mayank2k2** [comment]
This is tested now it is working fine
