### ISSUE TITLE
system requirment page

### ISSUE THREAD

**Issue by sumitmago** [OUPMATH/OxfordMath_UAT#67]
i think we should write system resolution as 1024 X 768 instead of other way.
![system requirement](https://cloud.githubusercontent.com/assets/13584396/13007388/ff6bf0ee-d1b5-11e5-92a4-cc21f89079da.PNG)

**Comment by mouparnadas** [comment]
The suggestion has been implemented and will be available in next deployment

**Comment by mayank2k2** [comment]
fixed so closing
