### ISSUE TITLE
Cookie policy

### ISSUE THREAD

**Issue by preetishah** [OUPMATH/OxfordMath_UAT#68]
Cookie policy link should redirect to UK cookie link and not open page in Oxford Maths

**Comment by mouparnadas** [comment]
The cookie policy link is working fine. 
![cookiepage](https://cloud.githubusercontent.com/assets/17062939/13071415/3440bc68-d4b9-11e5-8bd3-394b75d0af98.JPG)

**Comment by mouparnadas** [comment]
This is now working accordingly.

**Comment by preetishah** [comment]
Closed #68
