### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by preetishah** [OUPMATH/OxfordMath_UAT#69]
About us Rename as About as 

About us means about oxford university Press

**Comment by mouparnadas** [comment]
@mayank2k2 Please confirm this.

**Comment by manasghosh81** [comment]
Hi Mayank, Please confirm what the actual text would be.

**Comment by mayank2k2** [comment]
Can you confirm , whether the text is "About as" or "About" instead of "About us"

**Comment by preetishah** [comment]
This is small observation, 
1.       “About Us” on website usually means about the Organisation  like on OUPI website  https://india.oup.com/about
2.       If we want to write about Oxford Maths then this header should change to “ About” like it is referred in achiever website http://www.oxfordachiever.co.in/about

**Comment by mouparnadas** [comment]
Corrected the text to "About"
