### ISSUE TITLE
Download Upload Error

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#7]
[Download Upload Error.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/116878/Download.Upload.Error.docx)
Step 1: Login with admin user, search school "test school 11"
Step 2: click on upload icon
Step 3: Click on File link with status "Error present" 

Issue: Getting unexpected error
Expected : Error file should download without any issue

**Comment by manasghosh81** [comment]
This issue has been fixed.

**Comment by manasghosh81** [comment]
This is fixed now and availble in UAT for retest

**Comment by mayank2k2** [comment]
this is fixed
