### ISSUE TITLE
Top navigation FAQ 

### ISSUE THREAD

**Issue by preetishah** [OUPMATH/OxfordMath_UAT#70]
Please add more filter option in FAQ category to check the user interface.
[OM 1.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/132023/OM.1.docx)

**Comment by mouparnadas** [comment]
The FAQ page is work in progress as communicated in release mail.

**Comment by manasghosh81** [comment]
Development  of this page is still work-in progress.So please do to test this page.Once we put fully functional FAQ page we will ,we will consider this defect at later stage.
