### ISSUE TITLE
Top navigation contact us

### ISSUE THREAD

**Issue by preetishah** [OUPMATH/OxfordMath_UAT#71]
while sending and email to registered email ID, my outlook was open, ideally it should have opened a new mail with that email but I got the error attached

[OM1.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/131907/OM1.docx)

**Comment by manasghosh81** [comment]
This is not a valid defect .It will try to open mail client and putting the email id that is given in contact us page.

**Comment by mayank2k2** [comment]
This is not a defect, this issue is happening only in IE due to browser setting.
