### ISSUE TITLE
UX QA from OUP CDS —Round 2

### ISSUE THREAD

**Issue by CDS123** [OUPMATH/OxfordMath_UAT#74]
[OM QA Round 2.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/132318/OM.QA.Round.2.xlsx)

Round 2 sheet attached.

**Comment by mayank2k2** [comment]
Please mark  the lebel.

**Comment by manasghosh81** [comment]
These are set of UI changes.UI developer is working on it

**Comment by mouparnadas** [comment]
The changes have been implemented.

**Comment by mayank2k2** [comment]
you can do it later

**Comment by manasghosh81** [comment]
@mayank2k2 : Pls defer it

**Comment by mayank2k2** [comment]
@CDS123 : could you please review and close this as this is pending from long time.

**Comment by sumitmago** [comment]
hi Bindu, Kasturi, is it duplicate of #91

**Comment by CDS123** [comment]
Yes, it is. Closing this!
