### ISSUE TITLE
Unable to upload Student excel

### ISSUE THREAD

**Issue by sudhanshu2016** [OUPMATH/OxfordMath_UAT#75]
Error: User name not present in database.

**Comment by sudhanshu2016** [comment]
To 
Sumit/Kapil

loged in Created School isuues with Upload teacher & student Data.

**Comment by sudhanshu2016** [comment]
Hi upload successful. Issue resolve.

**Comment by sudhanshu2016** [comment]
teacher upload sucessful

**Comment by manasghosh81** [comment]
If this is working, can you please close the defect?

**Comment by mayank2k2** [comment]
closing this as this is working
