### ISSUE TITLE
templet of user does not consist telengana state

### ISSUE THREAD

**Issue by LALITOUP** [OUPMATH/OxfordMath_UAT#76]
while uploading  excel format  of students and teachers option of download templet is there in that while entering state telengana is not there though while registering a new school  it is shown

**Comment by manasghosh81** [comment]
The excel is pending with Soma for review for the instruction worksheet. Also there is a discussion on whether to capture address or not, so this has not been updated yet.

**Comment by mouparnadas** [comment]
Updated the bulk upload excel as per comments given by Kirti date 19/2
Also this is updated to make the address fields as blank

**Comment by sumitmago** [comment]
hi Lalit,
     could you please check and close if resolved to your satisfaction.

regards
Sumit

**Comment by mayank2k2** [comment]
this is fine
