### ISSUE TITLE
Unable to upload Teachers for New school

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#78]
Login with OUP Admin, Create new school. mine is "test noida school"
I have teachers list, try to validate,  it says 
"Error: Duplicate teacher for same class code and section."

Teachers should be uploaded for new school. attached the error file.

[Upload_User_Template_V1.0111_Error.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/137646/Upload_User_Template_V1.0111_Error.xlsx)

**Comment by manasghosh81** [comment]
This is not a valid defect since at  point of time there should be only Teacher exist in a particular class-section

**Comment by mayank2k2** [comment]
Can you validate the error file why I am getting the below error for teacher upload
[Upload_User_Template_V1.0_Error.xlsx](https://github.com/OUPMATH/OxfordMath_UAT/files/137852/Upload_User_Template_V1.0_Error.xlsx)

**Comment by mayank2k2** [comment]
Can you validate the error file why I am getting the below error for teacher upload

Error: Subscription count exceeded. Current Subcription count is 100

**Comment by mouparnadas** [comment]
This is now fixed.

**Comment by mayank2k2** [comment]
Working fine
