### ISSUE TITLE
Multiple Usability issues

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#79]
There are 4 usability issue found.
1. **"Select school" Drop down**: Searching for school is very difficult, It will be more difficult if we have more than 100 schools.  i suggest to have editable drop down where i can type few character so that list will be sorter to choose/select school.  
2. **Calendar Control**: Selecting last/next year date is very difficult, use easy navigated calendar control, also no way to see current date.
3. "**Left Navigation Pane**": it always goes to collapse mode after select any icon, if i expanded once it should be expanded mode until i collapse and similarly if i collapse it, it should be in collapse mode until i expand it. similar to other navigation pane eg. outlook
4: Advance Search: Controls are not properly placed as in below screen shot.
![image](https://cloud.githubusercontent.com/assets/16239450/13172144/a91c4b82-d71c-11e5-83ce-c8b2e9aeb7d8.png)

**Comment by manasghosh81** [comment]
Hi Mayank,
This is Subha. Sorry, I cannot take these issues as bug. Secondly, 
1) School Dropdown is sorted. It will take some efforts to implement type ahead now. With such a short time, we cannot do it now.
2) Calendar control was always that way starting the beginning, not sure why this becomes an issue now. This is a generic calendar control and most of the sites use it. - I am checking with my developers whether this can be done easily, otherwise we will not be doing it now.
3) It was decided like this during the UX design only. Look and feel will not be good if this stays on.
4) Is not replicable.

Regards
Subha

**Comment by mayank2k2** [comment]
Hello Subha,

These issues are raised by multiple stakeholder to me and some of these issues has been raised during FSD review as well.
We also keep in mind that Oxford Math website needs to be user friendly. I have discuss this with Sumit.  

Please let me know if you want to discuss.

Thanks,
Mayank

**Comment by manasghosh81** [comment]
Following will be reviewed and taken up later:
- Calendar control change

Following to be retained as-is
- Left navigation slider

Following will be re-checked by Mayank
- Advance search controls

TCS is looking into the following:
- Select school dropdown

**Comment by mouparnadas** [comment]
As per the discussion over the call, the look ahead feature in "Select School" drop down in advance search has been added. Please review.

**Comment by mayank2k2** [comment]
please review text is cutting

![image](https://cloud.githubusercontent.com/assets/16239450/13453631/9aff0062-e077-11e5-88a3-e5f9b3512223.png)

**Comment by mayank2k2** [comment]
Please use below url to see how it should look like
http://bootstrap-combobox-test.herokuapp.com/

**Comment by manasghosh81** [comment]
@mayank2k2 : Pls check the dropdown and defer this.

**Comment by mayank2k2** [comment]
take the help from airtel money

![image](https://cloud.githubusercontent.com/assets/16239450/13489939/c28e4d76-e14f-11e5-8ccc-46791cb8583a.png)

**Comment by manasghosh81** [comment]
Calendar control:Today's date is selected now
This is available in UAT now

**Comment by mayank2k2** [comment]
fine
