### ISSUE TITLE
Download Error Excel Crashes

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#8]
[Download Error Excel Crashes.docx](https://github.com/OUPMATH/OxfordMath_UAT/files/116884/Download.Error.Excel.Crashes.docx)
Step 1: Login with admin user, search school "test school 11"
Step 2: click on upload icon
Step 3: Click on File link for "4 feb" with status "Error present" 
Step 4: File downloaded now open the file

Issue: Getting error messages
Expected : File should open without any message

Issue: if we press "yes"
Expected : Excel goes hang and we need to kill the excel instance from Task manager.

**Comment by manasghosh81** [comment]
It is a duplicate issue (Issue # 7)

**Comment by mayank2k2** [comment]
now excel is not crashing
