### ISSUE TITLE
Create notification for selected students

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#81]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Teacher login login credential and click on login.
Step 3  Click on the create notification button from the dashboard
Step 4  Select a class and from the student selection dropdown select some student. Fill other mandatory details and click on send/schedule
Step 5  Click on the (..)

(Step 4)Present functionality: Not able to select students from drop-down. See screenshot.
![image](https://cloud.githubusercontent.com/assets/16831643/13213338/2e46baba-d96e-11e5-9ddb-9cc374d683bb.png)

(Step 4)Required functionality: 'Select students' dropdown should populate all the students of all sections.

(Step 5)Present functionality: Only student's name and roll number are appearing in pop up. See screenshot.
![image](https://cloud.githubusercontent.com/assets/16831643/13213351/4a3b3c00-d96e-11e5-88ef-4457a4431b48.png)

(Step 5)Required functionality: It should also show student's class and section in the pop up.

**Comment by mouparnadas** [comment]
- For the first part, it is not a defect as the "Select All" is shown in the section drop down and thus by default "Select All" is shown in the Student drop down. 
- Student drop down will only get populated if you explicitly select a section from the Section drop down
- Regarding class and section in popup we have added it
