### ISSUE TITLE
Not getting emails while registering for new school

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#83]
Hi Manas/Subha,
I am not getting emails while registering for new school, this was working earlier, Are you getting the email ?

**Comment by mouparnadas** [comment]
Tested in UAT and receiving mail.
This can be invalid mail issue.

![mail](https://cloud.githubusercontent.com/assets/17062939/13395624/f74d87e8-df15-11e5-9a84-bd467d53813a.JPG)

**Comment by mayank2k2** [comment]
working fine now
