### ISSUE TITLE
Student name not hyperlink in advance search

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#84]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Teacher login login credential and click on login.
Step 3  Click on the “advance search” against the student search.
Step 4  Provide student first/last/middle name, login id, registration start and end date and click on search

Required functionality: Student details should be generated below with roll no, student name(hyperlink), class section  and login id as details.
Present functionality: Student name is not a hyperlink.

**Comment by manasghosh81** [comment]
This is not a defect.As per our standard we have made all the search result contain a edit button which will open the detail page in editable mode.

Please close the defect.

**Comment by kirti-sharma** [comment]
Again this was mentioned in teacher test cases!
