### ISSUE TITLE
Teacher profile - gender update!

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#85]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Teacher login login credential and click on login.
Step 3  Click on the teacher name link
Step 4  Try to update the personal details

Required functionality: The teacher should be able to change the values for first, middle and last name, contact no and email id of the teacher.
Present functionality: Gender is also changeable. Pincode validation not proper.

**Comment by manasghosh81** [comment]
Hi Kirti,
The  gender is changeable because as decided in our FSD discussion meeting this required because if by mistake a wrong gender is assigned ,then Teacher can change it by themselves.

Current contact validation is 6 digit numeric only which is working fine.

**Comment by kirti-sharma** [comment]
Alright, gender was mentioned in the expected result of test case.
Address details are no longer there on this page, so pincode validation issue is irrelevant now.
