### ISSUE TITLE
Reset button not present

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#86]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Teacher login credential and click on login.
Step 3  Click on the teacher name link
Step 4  Try to update the values for personal and address details
Step 5  Click on the reset button

Present functionality: Reset button is missing

**Comment by mouparnadas** [comment]
Reset button added on edit profile. The change will be available in next deployment.

**Comment by manasghosh81** [comment]
This is fixed in UAT. Please recheck and close

**Comment by kirti-sharma** [comment]
Fixed
