### ISSUE TITLE
Pincode validation not proper

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#87]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Teacher  login credential and click on login.
Step 3  Give the student first name and/or last name or do an advance search
Step 4  Check the student search result grid
Step 5  Check the action column
Step 6  Click on the edit icon 
Step 7  Try to edit student's personal details and address details.
Step 8  Click on save button

Present functionality: System is accepting pincode with less than 6 digits.  
Required functionality: Fix as per standards.

**Comment by mouparnadas** [comment]
Pin-code validation has been corrected as per discussion with Soma, 6 digits always

**Comment by kirti-sharma** [comment]
Address details not appearing on profile page.

**Comment by mouparnadas** [comment]
As per recent review by OUP security team, we have hidden the address details.
Address details will not be available.
For further details please contact Sumit Mago.
