### ISSUE TITLE
Mouseover text in 'Edit Task'

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#88]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Teacher login login credential and click on login.
Step 3  Click on the classes link
Step 4  Click on the search task button on the dashboard
Step 5  "Fill the details like Class (Selected from dropdown)
Section (Selected from dropdown)
Chapter (Selected from dropdown)
Topic (Selected from dropdown)
Start date and end date and click on search"
Step 6  Check the search grid 
Step 7  Click on the edit icon on the Action column of a task

Present functionality: Mouseover edit icon shows 'Edit Task'. 
Required functionality: Change the mouseover text to 'View/Edit Task'

**Comment by manasghosh81** [comment]
This is a usability change .We will modify the text

**Comment by mouparnadas** [comment]
The changes will be available in next deployment.

**Comment by manasghosh81** [comment]
This is fixed and available in UAT .Please recheck and close

**Comment by kirti-sharma** [comment]
Implemented.
