### ISSUE TITLE
Casing issues in "Teacher login" under "Reports" tab

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#89]
Please correct these casing issues in "Teacher login" under "Reports" tab.

![casing errors 2-teacher login](https://cloud.githubusercontent.com/assets/16831474/13315422/95752942-dbd0-11e5-8e01-f71eeb06de15.png)
![casing errors 1-teacher login](https://cloud.githubusercontent.com/assets/16831474/13315335/332d9530-dbd0-11e5-8c8a-12a897938218.png)
![casing errors-teacher login](https://cloud.githubusercontent.com/assets/16831474/13315336/333a5fa4-dbd0-11e5-8b2d-2b10f87603ac.png)

**Comment by mouparnadas** [comment]
@madhumitadey - as per discussion between Subha, Soma, yourself and Kirti in a meeting it was decided that the heading should have been init-caps format. All headings and labels are changed based on that. Why do we need to change it again?

**Comment by somabanerjee** [comment]
@manasghosh81 / mouparnadas  Hi!  Headline style capitalization was what was discussed and agreed to. However, headline-style does not mean indiscriminate init-cap. Prepositions, subjunctive conjunctions, etc. continue to be lowercased. Kindly make all fixes as per editorial recommendations.

**Comment by mouparnadas** [comment]
Please validate. the changes have been implemented.
