### ISSUE TITLE
Casing issue in "Teacher login" under "Create Notifications" tab

### ISSUE THREAD

**Issue by madhumitadey** [OUPMATH/OxfordMath_UAT#90]
Correct the casing issue in "Teacher login" under "Create Notifications" tab.
![casing errors 3-teacher login](https://cloud.githubusercontent.com/assets/16831474/13315516/101a6cc0-dbd1-11e5-8621-478964e3d2ed.png)

**Comment by mouparnadas** [comment]
Related to #89

**Comment by manasghosh81** [comment]
This is a text change suggested by editorial team.This will be implemented

**Comment by mouparnadas** [comment]
Fixed. The change will be available in next deployment.

**Comment by manasghosh81** [comment]
This is fixed and available in UAT now.Please recheck and close it
