### ISSUE TITLE
Down arrow should not have double lines

### ISSUE THREAD

**Issue by pkasturirangan** [OUPMATH/OxfordMath_UAT#91]
TCS: to be discussed when chandan is in meeting as TCS needs to call back the creative person 

![1](https://cloud.githubusercontent.com/assets/17135982/13316294/54801a78-dbd5-11e5-88a8-2ca36fef1078.jpg)

**Comment by manasghosh81** [comment]
Hi Kasturi,

This is Subha. Sumit, Bindu and myself had a long discussion regarding this and it had been decided that we are not going to do this now. Please refer to issue #74 (UX QA from OUP CDS —Round 2)

Appreciate if you can close it

Regards
Subha

**Comment by pkasturirangan** [comment]
Hi Subha

This issue is marked as 'On Hold' in the excel sheet and so I have not closed it. 

regards

Kasturi

**Comment by sumitmago** [comment]
hi,
    please defer it for time being.

**Comment by mayank2k2** [comment]
issues is fixed
