### ISSUE TITLE
Contact validation on teacher profile page

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#93]
Step 1 Open the OUP my maths url in a browser
Step 2 Provide the Teacher login login credential and click on login.
Step 3 Click on the teacher name link
Step 4 Try to update the personal details

Required functionality: Validation of 'Contact' is not proper. Please fix.

**Comment by manasghosh81** [comment]
@kirti-sharma : This is Subha. We have done the contact number validation as per rules mentioned by Kapil. i.e. 12 digits or less. It is working as per that rule in UAT for our sample teacher. Can you please double check?

**Comment by kirti-sharma** [comment]
Fine Subha. It is working for as per the above rule.
