### ISSUE TITLE
Class sorting 

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#94]
Class name should be sorted by class code 
![image](https://cloud.githubusercontent.com/assets/16239450/13351409/7a1a59b0-dcac-11e5-9b1f-803cc71c36e1.png)

**Comment by manasghosh81** [comment]
@mayank2k2 : This is Subha. All data in the dropdown should be sorted on the actual data that is present in the dropdown. If some school gives the class name as 
class code= 03, class name = Zebra
class code = 04, class name = Apple
- then if we sort on class code, Zebra will come before Apple, and every user tries to find based on alphabetic order in any dropdown. So all dropdowns are sorted on the actual value inside the dropdown.

**Comment by mayank2k2** [comment]
@subha:  It should be sorted on two levels: First by class code and then by class name.

**Comment by manasghosh81** [comment]
@Mayank:

This will not solve your purpose.Since we dont have data with different class name with same class code.If the list filter out first with class code,then class name filter will not do anything

Please discuss with business team and we will put the sort criteria either class code or class name

**Comment by sumitmago** [comment]
Hi,
               Normally, classes would be named as ‘Class <class no> + <Section name>’. for e.g. Class 1 a or Class 1 sunflower.

So my view is to sort them on class code and then on class name (alphabetically).

Soma, your views please?

Thanks & Regards
Sumit Mago
Head (Digital Solutions) – Learning & Assessment
Oxford University Press
2nd Floor, Tower-1, Stellar Crest  Business Center, IT Park, C-25 Sector 62,  Noida
(D) - 0120-6718900 Extn - 214, (M) +91-9873299973

The ABC of Innovation:
Conceive
Believe
Achieve

**Comment by mayank2k2** [comment]
how can you have data with different class name with same class code for a school i don't understand.

please discuss if you have miss understood

**Comment by manasghosh81** [comment]
As discussed in our Triage meeting we will sort this class dropdown based on class code

**Comment by mouparnadas** [comment]
The sorting implemented based on class code. the change will be available in next deployment.

**Comment by manasghosh81** [comment]
The fix is available in UAT now.Please recheck this

**Comment by mayank2k2** [comment]
It look the classes are sorted by class code but why 2 same class name "Three" is displaying in below screenshot
![image](https://cloud.githubusercontent.com/assets/16239450/13453706/22d3c220-e078-11e5-8053-b6085fd89913.png)

**Comment by mayank2k2** [comment]
working fine
