### ISSUE TITLE
user name should not contains spaces

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#96]
Usernames can contain letters (a-z, A-Z), numbers (0-9), underscore (_)
I have 2 usernames with spaces in between
Student 13 A
Teacher3 A

if there is space then replace with underscores (_)

**Comment by mouparnadas** [comment]
Fixed QA. This will be available in next UAT deployment.

**Comment by manasghosh81** [comment]
This is an enhancement which is available in UAT now.Please recheck and close it

**Comment by mayank2k2** [comment]
working fine
