### ISSUE TITLE
Assigned lessons/OHs are not loading from student login

### ISSUE THREAD

**Issue by kirti-sharma** [OUPMATH/OxfordMath_UAT#97]
Step 1  Open the OUP my maths url in a browser
Step 2  Provide the Student login credential and click on login.
Step 3  Check the My task drpdown on the dashboard
Step 4  Select any value from the dropdown
Step 5  Check the task tile
Step 6  Click on the tile itself
Step 7  Click on start OH or lesson button

Present functionality: Assigned lessons/OHs are not loading from student login.
Required functionality: Student should be able to navigate through the screen.

**Comment by mouparnadas** [comment]
This is working fine. Please clear cache and try again.

**Comment by kirti-sharma** [comment]
It is working okay now.
