### ISSUE TITLE
Unable to upload after successfully validated for new school

### ISSUE THREAD

**Issue by mayank2k2** [OUPMATH/OxfordMath_UAT#99]
I created new school, validated the users for upload, validation successful with status "No error" but  Upload failed without any file to download.

![image](https://cloud.githubusercontent.com/assets/16239450/13418899/a809ea3e-df9f-11e5-846b-3e98e0ffc480.png)

**Comment by manasghosh81** [comment]
As discussed in defect triage, Mayank to test the update again after removing the formula in the excel.

**Comment by mayank2k2** [comment]
working
